### ISSUE TITLE
Upload expanded map

### ISSUE THREAD

**Issue by moderncocoafarmer** [moderncocoafarmer/MCF#37]
#12

**Comment by moderncocoafarmer** [comment]
This has now been done and added to the drive , the mosque should fit with the new background ;
game>parents level> final assets >Background >final bigger background. The old screen is in the centre of the image , so if centred in unity should be fine x

**Comment by AlanWills** [comment]
Excellent - well done for having the foresight to make it so that it will still fit with the google maps intro.
