### ISSUE TITLE
Clean up Google Drive

### ISSUE THREAD

**Issue by AlanWills** [moderncocoafarmer/MCF#50]
Currently (especially for the parent's level) the google drive assets are not grouped and confusingly named.  For example, the Instructions for the Parent's Level are in the root of the drive & sprites for the Parent's Level are split over (at least) three folders - `Final Assets`, `Placeholders` and confusingly, a folder in `Placeholders` called `Sprites`.

Some of the assets in `Placeholders` are also not place holders.

This must be cleaned up and a common structure/naming convention used for the parent's level and all future levels we create.

Here is what I suggest:

Each level has the following folders:

- Sprites
- Audio
- Video
- Fonts
- Text?
- etc.

Each folder inside should have properly named sub-folders:

-Sprites:
     - UI
     - Buildings
     - People

etc.

**Comment by moderncocoafarmer** [comment]
I came on here to close this and then read what you had written..
Might need a few mins

**Comment by moderncocoafarmer** [comment]
ok this is done now for parents level I think
