### ISSUE TITLE
real 'Abduction' sound under sound effects in drive 'Abduction'

### ISSUE THREAD

**Issue by moderncocoafarmer** [moderncocoafarmer/MCF#52]

**Comment by AlanWills** [comment]
What is the abduction sound for?  When should it be used?

**Comment by moderncocoafarmer** [comment]
It should be used when a child is trafficked instead of the current 'well sound'

**Comment by AlanWills** [comment]
We have an abduction sound already from Jade though.

**Comment by moderncocoafarmer** [comment]
Ok, wasn't sure if you had already uploaded it or not 
was different in the demo version so I assumed

**Comment by moderncocoafarmer** [comment]
if you have most recent then this can be closed
