### ISSUE TITLE
Show data dialog when clicking on Child Indicator

### ISSUE THREAD

**Issue by AlanWills** [moderncocoafarmer/MCF#66]
Now we have added UI to the map to indicate where children are, we can start improving UX.  We could click on it to show the data dialog for example.  Have a think about other things we can do.

**Comment by AlanWills** [comment]
Make the indicators to do with child's health too, so the user is more easily able to keep tabs on their children.

**Comment by AlanWills** [comment]
Data dialog opens up now - any other ideas?

**Comment by moderncocoafarmer** [comment]
Click on name once and dialogue opens, is great :)
click again on name in map and it should close the dialogue box.  No need for the x in the corner.
