### ISSUE TITLE
Add Progress Bars to Child Indicators

### ISSUE THREAD

**Issue by AlanWills** [moderncocoafarmer/MCF#68]
We can very easily add progress bars to the Child Indicators.  It will be a doddle.  Think about the design - do we add a small bar or make the whole UI the bar?

**Comment by moderncocoafarmer** [comment]
I think the whole bar should be the progression bar, let's have green filling the bar up from left to right.  (feel free to change the text box to one with right angled corners to make it easier)

**Comment by moderncocoafarmer** [comment]
![progression bar](https://user-images.githubusercontent.com/26073223/27557303-fef20b14-5ab0-11e7-8cd0-5782bf1abba4.png)

**Comment by moderncocoafarmer** [comment]
(this colour)
