### ISSUE TITLE
Ability to enter a value of your choosing for the donation

### ISSUE THREAD

**Issue by moderncocoafarmer** [moderncocoafarmer/MCF#71]
After many discussions with people I have decided that this would be a good idea, to allow children to use the app and do micro donations, i.e 5 and 10 p at a time.  (We will need to talk about the effect of 'real donation' on the game , 5 p vs 10 p and so on).

**Comment by AlanWills** [comment]
I agree that I think smaller donations are much more likely to actually get people to donate - after all the game is simple so why should people put a tonne of money into it.

**Comment by AlanWills** [comment]
Email Ian Bretman.

**Comment by moderncocoafarmer** [comment]
Have sent an email now, let's wait and see, would be great to get onto this as a priority.

**Comment by AlanWills** [comment]
I've implemented this, but there needs design about max values and ring fencing of funds.
